### ISSUE TITLE
Various bugs with God Mode

### ISSUE THREAD

**Issue by KittyTristy** [WizardSpire/roguekit#59]
So here are a few bugs I've noticed with God Mode ever since certain bits of code were migrated into separate files.

- [ ] God Mode cannot be disabled in certain circumstances<br>
(the equipment modifier cannot be reset, for example, if the game has been saved, exited, and reloaded later)
- [ ] Walking through walls (broken feature)
- [ ] "Invisibility" to monsters (also a broken feature)

**Comment by cptmashek** [comment]
This is no longer an issue with the current code (we do not have a god mode implemented yet).
